// Generated by CoffeeScript 1.7.1
var TictactoeApp;

TictactoeApp = angular.module("TictactoeApp", []);

TictactoeApp.controller("TictactoeAppCtrl", [
  "$scope", function($scope) {
    var i, newTile, status_idicators;
    status_idicators = $("#teams li");
    $scope.tiles = [];
    $scope.players = [
      {
        name: "Ernie",
        marker: "X",
        img_url: "img/ernie.jpg",
        indicator: $(status_idicators[0]),
        combo: []
      }, {
        name: "Bert",
        marker: "O",
        img_url: "img/bert.jpg",
        indicator: $(status_idicators[1]),
        combo: []
      }
    ];
    $scope.current_player = $scope.players[0];
    $scope.turns = 0;
    $scope.win_combos = [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]];
    i = 0;
    while (i < 9) {
      newTile = {
        tilevalue: "",
        tileNum: i,
        active: false
      };
      i += 1;
      $scope.tiles.push(newTile);
    }
    $scope.handle_click = function(tile) {
      if (tile.active === false) {
        tile.tilevalue = $scope.current_player.marker;
        tile.active = true;
        $scope.current_player.combo.push(tile.tileNum);
        $scope.turns += 1;
        if ($scope.is_win($scope.current_player) !== true && $scope.is_tie($scope.current_player) !== true) {
          if ($scope.turns % 2 === 0) {
            return $scope.current_player = $scope.players[0];
          } else {
            return $scope.current_player = $scope.players[1];
          }
        }
      }
    };
    $scope.is_win = function(current_player) {
      var check_combo;
      i = 0;
      while (i < $scope.win_combos.length) {
        check_combo = current_player.combo.intersect($scope.win_combos[i]);
        i += 1;
        if (check_combo.length === 3) {
          return true;
        }
      }
    };
    $scope.is_tie = function(current_player) {
      var check_combo;
      i = 0;
      while (i < $scope.win_combos.length) {
        check_combo = current_player.combo.intersect($scope.win_combos[i]);
        i += 1;
        if (check_combo.length !== 3 && current_player.combo.length === 5) {
          return true;
        }
      }
    };
  }
]);
